using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GBCSporting_LAIR.Models
{
  internal class CountryConfig : IEntityTypeConfiguration<Country>
  {
    // Stores countries to be used in customer mvc
    public void Configure(EntityTypeBuilder<Country> entity)
    {
      entity.HasData(
        new Country { Id = 1, Name = "Afghanistan" },
        new Country { Id = 2, Name = "Algeria" },
        new Country { Id = 3, Name = "Argentina" },
        new Country { Id = 4, Name = "Australia" },
        new Country { Id = 5, Name = "Austria" },
        new Country { Id = 6, Name = "Bahamas" },
        new Country { Id = 7, Name = "Bangladesh" },
        new Country { Id = 8, Name = "Belarus" },
        new Country { Id = 9, Name = "Belgium" },
        new Country { Id = 10, Name = "Bhutan" },
        new Country { Id = 11, Name = "Bolivia" },
        new Country { Id = 12, Name = "Botswana" },
        new Country { Id = 13, Name = "Brazil" },
        new Country { Id = 14, Name = "Brunei" },
        new Country { Id = 15, Name = "Bulgaria" },
        new Country { Id = 16, Name = "Cambodia" },
        new Country { Id = 17, Name = "Cameroon" },
        new Country { Id = 18, Name = "Canada" },
        new Country { Id = 19, Name = "Chile" },
        new Country { Id = 20, Name = "China" },
        new Country { Id = 21, Name = "Colombia" },
        new Country { Id = 22, Name = "Costa Rica" },
        new Country { Id = 23, Name = "Croatia" },
        new Country { Id = 24, Name = "Cuba" },
        new Country { Id = 25, Name = "Czechia (Czech Republic)" },
        new Country { Id = 26, Name = "Democratic Republic of the Congo" },
        new Country { Id = 27, Name = "Denmark" },
        new Country { Id = 28, Name = "Dominican Republic" },
        new Country { Id = 29, Name = "Ecuador" },
        new Country { Id = 30, Name = "Egypt" },
        new Country { Id = 31, Name = "El Salvador" },
        new Country { Id = 32, Name = "Equatorial Guinea" },
        new Country { Id = 33, Name = "Ethiopia" },
        new Country { Id = 34, Name = "Finland" },
        new Country { Id = 35, Name = "France" },
        new Country { Id = 36, Name = "Georgia" },
        new Country { Id = 37, Name = "Germany" },
        new Country { Id = 38, Name = "Greece" },
        new Country { Id = 39, Name = "Iceland" },
        new Country { Id = 40, Name = "India" },
        new Country { Id = 41, Name = "Indonesia" },
        new Country { Id = 42, Name = "Iran" },
        new Country { Id = 43, Name = "Iraq" },
        new Country { Id = 44, Name = "Ireland" },
        new Country { Id = 45, Name = "Israel" },
        new Country { Id = 46, Name = "Italy" },
        new Country { Id = 47, Name = "Liberia" },
        new Country { Id = 48, Name = "Macedonia" },
        new Country { Id = 49, Name = "Malaysia" },
        new Country { Id = 50, Name = "Mexico" },
        new Country { Id = 51, Name = "Netherlands" },
        new Country { Id = 52, Name = "New Zealand" },
        new Country { Id = 53, Name = "North Korea" },
        new Country { Id = 54, Name = "Philippines" },
        new Country { Id = 55, Name = "Poland" },
        new Country { Id = 56, Name = "Portugal" },
        new Country { Id = 57, Name = "Qatar" },
        new Country { Id = 58, Name = "Russia" },
        new Country { Id = 59, Name = "Saudi Arabia" },
        new Country { Id = 60, Name = "Serbia" },
        new Country { Id = 61, Name = "Singapore" },
        new Country { Id = 62, Name = "South Africa" },
        new Country { Id = 63, Name = "South Korea" },
        new Country { Id = 64, Name = "Sweden" },
        new Country { Id = 65, Name = "Switzerland" },
        new Country { Id = 66, Name = "Syria" },
        new Country { Id = 67, Name = "Tanzania" },
        new Country { Id = 68, Name = "Thailand" },
        new Country { Id = 69, Name = "Turkey" },
        new Country { Id = 70, Name = "Uganda" },
        new Country { Id = 71, Name = "Ukraine" },
        new Country { Id = 72, Name = "United Arab Emirates" },
        new Country { Id = 73, Name = "United Kingdom" },
        new Country { Id = 74, Name = "United States of America" },
        new Country { Id = 75, Name = "Uruguay" },
        new Country { Id = 76, Name = "Venezuela" },
        new Country { Id = 77, Name = "Vietnam" },
        new Country { Id = 78, Name = "Wakanda" },
        new Country { Id = 79, Name = "Wonderland (Your name must be Alice)" },
        new Country { Id = 80, Name = "Zimbabwe" }
        );
    }
  }
}
